# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: artic-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
# conda-forge packages
#  - conda-forge::biopython=1.79              #py36h7b4949f_1
#  - conda-forge::pandas=0.25.3 #=1.0.5                #py36hcc1bba6_0
#  - conda-forge::r-argparse #=2.0.3            #r40hc72bb7e_1
#  - conda-forge::r-cowplot #=1.1.0             #r40h6115d3f_0
#  - conda-forge::r-data.table #=1.13.4         #r40h066c5db_0
#  - conda-forge::r-ggforce #=0.3.3             #r40h9951f98_0
#  - conda-forge::r-gplots #=3.1.1              #r40hc72bb7e_0
#  - conda-forge::r-gridextra #=2.3             #r40h6115d3f_1003
#  - conda-forge::r-hrbrthemes #=0.8.0          #r40h6115d3f_1
#  - conda-forge::r-markdown #=1.1              #r40h17f1fa6_1
#  - conda-forge::r-optparse #=1.6.6            #r40h6115d3f_1
#  - conda-forge::r-svglite #=1.2.3.2           #r40hc5da6b9_0
#  - conda-forge::r-tidyverse #=1.3.0           #r40h6115d3f_2
#  - conda-forge::r-viridis #=0.5.1             #r40h6115d3f_1004
#  - conda-forge::r-zoo #=1.8_8                 #r40h17f1fa6_0
#  - conda-forge::r-reshape2 #=1.8_8                 #r40h17f1fa6_0
#  - bioconda::bioconductor-biostrings #=2.58.0            #r40h8909d69_0
#  - bioconda::bioconductor-complexheatmap #=2.6.2         #r40_0
# bioconda packages
  - bioconda::artic=1.2.1
  - bioconda::bedtools #=2.29.2               #h37cfd92_0
  #- bioconda::bwa #=0.7.17                    #h2573ce8_7
  - bioconda::edirect
  - bioconda::mosdepth=0.2.9
  - bioconda::multiqc=1.11 #=1.9                   #py_1
  - bioconda::nanoplot=1.36.1
  # - bioconda::nextflow=20.10.0
  # - bioconda::porechop
  - bioconda::pycoQC=2.2.3
  #- bioconda::samtools #=1.10                 #hf7e01e7_3
  - pip
  - pip:
    - plotly